services:
  db:
    build:
      context: ./docker/postgres
    container_name: uptime-forge-db
    environment:
      POSTGRES_USER: uptime
      POSTGRES_PASSWORD: uptime
      POSTGRES_DB: uptime_forge
    ports:
      - "5444:5432"
    volumes:
      - uptime_forge_db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uptime -d uptime_forge"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: uptime-forge-pgadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: temporal
    image: dpage/pgadmin4:9.12
    ports:
      - 5051:80
    volumes:
      - uptime_forge_pgadmin:/var/lib/pgadmin
volumes:
  uptime_forge_db:
  uptime_forge_pgadmin:
